#注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    perferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
server:
  port: 9002
spring:
  application:
    name: ihrm-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.241.188:3306/ihrm?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    #格式化SQL
    #properties:
      #hibernate:
        #format_sql: true
  redis:
    host: 192.168.241.188
    port: 6379

my:
  appId: 15191935
  apiKey: cyWSHgas93Vtdmt42OwbW8pu
  secretKey: yf1GusMvvLBdOnyubfLubNyod9iEDEZW
  imageType: BASE64
  groupId: itcast
  url: http://localhost:8080/#/facelogin

jwt:
  config:
    key: saas-ihrm
    ttl: 3600000

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace